- hosts: all
  remote_user: ubuntu
  tasks:
  - name: Read file and set output as variable
    debug: {{ lookup('file','/home/ubuntu/ec2-ip.txt') }}
    register: ec2_instance_ip
    changed_when: false
  
  - name: Set endpoint URL as variable
    set_fact:
      ec2_instance_ip_variable: "{{ ec2_instance_ip.stdout }}"
# This might work, not tested
  - name: Get db endpoint URL
    debug: {{ lookup('file','/home/ubuntu/rds-url.txt') }}
    register: db_endpoint_url
    changed_when: false

  - name: Set endpoint URL as variable
    set_fact:
      db_endpoint_url_variable: "{{ db_endpoint_url.stdout }}"

  - name: Replace database endpoint url
    replace:
      path: rest/main/resources/application-mysql.properties
      regexp: 'localhost:3306'
      replace: "{{ db_endpoint_url }}"

  # frontend
  - name: Replace backend url
    replace:
      path: angular/environments/environment.ts
      regexp: 'localhost'
      replace: "{{ ec2_instance_ip.stdout_lines }}"
