For the dockerfiles, they'll want to be added to the frontend and backend folders. It still needs to grab the files in the folder to be able to run.

It needs docker, nginx and nodejs to run. Nginx version can be latest, but nodejs has only been tested on version 16.3-alpine. 
