- hosts: all
  remote_user: ubuntu
  become: yes
  vars:
    git_version: latest
    nginx_version: latest
    nginx_conf_file: /etc/nginx/nginx.conf
    java_version: openjdk-11-jdk
    docker_version: latest

  tasks:

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker and compose
    apt:
      name: 
        - docker-ce
        - docker-compose
      state: latest
      update_cache: true

  - name: Install Java
    shell: apt install -y openjdk-11-jre-headless 

  - name: Install nginx
    shell: apt install -y nginx

  - name: Install Node.js
    shell: apt install -y nodejs

  - name: copy to remote system
    copy: 
      src: docker-compose.yml
      dest: /home/ubuntu/docker-compose.yml
      owner: ubuntu

  - name: copy inv to remote system
    copy: 
      src: inventory.yaml
      dest: /home/ubuntu/inventory.yaml
      owner: ubuntu
      
  - name: copy ec2 file to remote
    copy: 
      src: ec2-ip.txt
      dest: /home/ubuntu/ec2-ip.txt
      owner: ubuntu
      
  - name: copy rds file to remote
    copy: 
      src: rds-url.txt
      dest: /home/ubuntu/rds-url.txt
      owner: ubuntu

  # runs the dockerswarm stuff
- hosts: all
  become: true
  roles:
    - dockerswarm







