---

tasks:
  - name: Init Swarm 
    command: "docker swarm init --advertise-addr {{ inventory_hostname }}"
    
  - name: Export Manager Token
    command: docker swarm join-token manager -q 
    register: swarm-manager-token

  - name: Show manager token
    debug: var=swarm-manager-token.stdout

  - name: Export Worker Token
    command: docker swarm join-token worker -q 
    register: swarm-worker-token

  - name: Show worker token
    debug: var=swarm-worker-token.stdout

  - name: Join swarm 
    hosts: docker_worker
    remote_user: ubuntu
    gather-facts: False
    vars:
      token: "{{ hostvars[groups['manager'][0]]['worker_token']['stdout'] }}"
      manager: "{{  }}"