---
  - name: Init Swarm
    hosts: docker_manager
    gather_facts: False 
    remote_user: ubuntu
    command: "docker swarm init --advertise-addr {{ inventory_hostname }}"
      
  - name: Export Manager Token
    command: docker swarm join-token manager -q 
    register: swarm-manager-token

  - name: Show manager token
    debug: var=swarm-manager-token.stdout

  - name: Export Worker Token
    command: docker swarm join-token worker -q 
    register: swarm-worker-token

  - name: Show worker token
    debug: var=swarm-worker-token.stdout

  - name: Join swarm 
    hosts: docker_worker
    remote_user: ubuntu
    gather-facts: False
    vars:
      token: "{{ hostvars[groups['manager'][0]]['worker_token']['stdout'] }}"
      manager: "{{ hostvars[groups['manager'][0]]['inventory_hostname'] }}"
    tasks:
      - name: Join Swarm Cluster as worker 
        command: docker swarm join --token {{ token }} {{ manager }}:2377 # 2377 is cluster management port
        register: worker

      - name: Show result 
        debug: var=worker.stdout

      - name: any errors 
        debug: var=worker.